# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_anisotropic_diffusion <- function(image, iterations, lambda, k) {
    .Call(`_anidiff_cpp_anisotropic_diffusion`, image, iterations, lambda, k)
}

